name: 00.toys.00.steamcmd

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          username: mewlody
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: bash .sh
        run: |
          cd 00.toys/00.steamcmd
          bash 00.toys.00.steamcmd.sh
