name: 02.ansible

on:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          username: mewlody
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: bash .sh
        run: |
          cd 02.ansible
          bash 02.ansible.sh
